version: '3.4'

services:
  hc.api:
    image: ${DOCKER_REGISTRY-}hcapi
    build:
      context: .
      dockerfile: HC.API/Dockerfile

  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: twosumdb
    ports:
      - "5432:5432"